export const genres = [
  "Fiction",
  "Non-fiction",
  "Mystery",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Thriller",
  "Biography",
  "History",
  "Self-help",
];

export const subjectMap: Map<string, string[]> = new Map([
  [
    "Arts",
    [
      "Architecture",
      "Art Instruction",
      "Art History",
      "Dance",
      "Design",
      "Fashion",
      "Film",
      "Graphic Design",
      "Music",
      "Music Theory",
      "Painting",
      "Photography",
    ],
  ],
  [
    "Fiction",
    [
      "Fantasy",
      "Historical Fiction",
      "Horror",
      "Humor",
      "Literature",
      "Magic",
      "Mystery and detective stories",
      "Plays",
      "Poetry",
      "Romance",
      "Science Fiction",
      "Short stories",
      "Thriller",
      "Young adult",
    ],
  ],
  [
    "Science and Mathematics",
    ["Biology", "Chemistry", "Mathematics", "Physics", "Programming"],
  ],
  [
    "Business and Finance",
    [
      "Management",
      "Entrepreneurship",
      "Business Economics",
      "Business Success",
      "Finance",
    ],
  ],
  [
    "Children's Books",
    [
      "Kids Books",
      "Stories in Rhyme",
      "Baby Books",
      "Picture Books",
      "Bedtime Books",
    ],
  ],
  [
    "History",
    [
      "Ancient Civilization",
      "Archaeology",
      "Anthropology",
      "World War II",
      "Social Life and Customs",
    ],
  ],
  [
    "Health and Wellness",
    [
      "Cooking",
      "Cookbooks",
      "Mental Health",
      "Exercise",
      "Nutrition",
      "Self-help",
    ],
  ],
  [
    "Biography",
    [
      "Autobiographies",
      "History",
      "Politics and Government",
      "World War II",
      "Women",
      "Kings and Rulers",
      "Composers",
      "Artists",
    ],
  ],
  [
    "Social Sciences",
    ["Anthropology", "Religion", "Political Science", "Psychology"],
  ],
  [
    "Textbooks",
    [
      "History",
      "Mathematics",
      "Geography",
      "Psychology",
      "Algebra",
      "Education",
      "Business & Economics",
      "Science",
      "Chemistry",
      "English Language",
      "Physics",
      "Computer Science",
    ],
  ],
]);
